include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - avoid_empty_else
    - avoid_types_as_parameter_names
    - cancel_subscriptions
    - close_sinks

analyzer:
  errors:
    invalid_annotation_target: ignore
